//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.03 at 12:47:39 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.samples.blog.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.blog.samples.webservices;
